controllers:
    resource: ../src/Controller/
    type: attribute

# config/routes.yaml
order_success:
    path: '/commande/merci/{stripeSessionId}'
    controller: 'App\Controller\OrderSuccessController::success'
    methods: ['GET']

update_preparation:
    path: '/admin/order/update-preparation/{id}'
    controller: 'App\Controller\Admin\OrderCrudController::updatePreparation'
    methods: ['GET', 'POST']
    requirements:
        id: '\d+'