# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

#    App\Controller\Admin\OrderCrudController:
#        arguments:
#            $entityManager: '@doctrine.orm.entity_manager'
#            $urlGenerator: '@easyadmin.router.admin_url_generator'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
